import { useEffect, useState, useRef } from 'react'
import { useTranslation } from 'react-i18next'
import { useNavigate } from 'react-router-dom'
import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'
import SkillTag from '../components/ui/SkillTag'
import LoadingSkeleton from '../components/ui/LoadingSkeleton'

export default function Step5Generating({ submitProfile, profile, loading, error }) {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const cardRef = useRef(null)
  const [generated, setGenerated] = useState(false)
  const [exporting, setExporting] = useState(false)

  useEffect(() => {
    if (!generated) {
      setGenerated(true)
      submitProfile().catch(() => {})
    }
  }, [])

  const handleDownloadPDF = async () => {
    if (!cardRef.current) return
    setExporting(true)
    try {
      const canvas = await html2canvas(cardRef.current, { scale: 2, useCORS: true })
      const imgData = canvas.toDataURL('image/png')
      const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
      const pdfWidth = pdf.internal.pageSize.getWidth()
      const pdfHeight = (canvas.height * pdfWidth) / canvas.width
      pdf.addImage(imgData, 'PNG', 0, 10, pdfWidth, pdfHeight)
      pdf.save('unmapped-skills-passport.pdf')
    } finally {
      setExporting(false)
    }
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="max-w-sm w-full px-6 text-center">
          <div className="w-12 h-12 border-4 border-teal-400 border-t-transparent rounded-full animate-spin mx-auto mb-6" />
          <p className="text-gray-600 font-medium">{t('generating_message')}</p>
          <p className="text-xs text-gray-400 mt-2">This takes about 10 seconds</p>
          <div className="mt-8">
            <LoadingSkeleton lines={4} />
          </div>
        </div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="max-w-sm w-full px-6 text-center">
          <p className="text-red-500 font-medium mb-4">{error}</p>
          <button onClick={() => navigate('/step4')} className="px-6 py-3 rounded-xl border border-gray-200 text-gray-600">
            Go back
          </button>
        </div>
      </div>
    )
  }

  if (!profile) return null

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-lg mx-auto px-4 py-8">
        <div className="text-center mb-6">
          <h2 className="text-xl font-bold text-gray-900">{t('profile_title')}</h2>
          <p className="text-sm text-gray-500 mt-1">This is yours. You own it.</p>
        </div>

        <div ref={cardRef} className="bg-white rounded-2xl border border-gray-100 p-6 space-y-5">
          <div className="flex items-start justify-between">
            <div>
              <p className="text-xs text-gray-400 uppercase tracking-wide mb-1">{t('profile_isco')}</p>
              <h3 className="text-lg font-semibold text-gray-900">{profile.skills.isco_title}</h3>
              <p className="text-xs text-gray-300 mt-0.5">ISCO {profile.skills.isco_codes[0]}</p>
            </div>
            <div className="w-12 h-12 rounded-full bg-teal-50 flex items-center justify-center">
              <span className="text-teal-600 text-xl font-bold">U</span>
            </div>
          </div>

          <p className="text-sm text-gray-600 leading-relaxed border-l-2 border-teal-200 pl-4">
            {profile.skills.summary}
          </p>

          <div>
            <p className="text-xs text-gray-400 uppercase tracking-wide mb-3">Your skills</p>
            <div className="flex flex-wrap gap-2">
              {profile.skills.esco_skill_tags.map(tag => (
                <SkillTag key={tag} label={tag} />
              ))}
            </div>
          </div>

          <div>
            <p className="text-xs text-gray-400 uppercase tracking-wide mb-3">Skill levels</p>
            <div className="space-y-2">
              {Object.entries(profile.skills.competency_levels).map(([domain, level]) => (
                <div key={domain} className="flex items-center justify-between">
                  <span className="text-sm text-gray-600 capitalize">{domain.replace(/_/g, ' ')}</span>
                  <span className={`text-xs font-medium px-2 py-0.5 rounded-full ${
                    level === 'advanced' ? 'bg-teal-50 text-teal-700' :
                    level === 'intermediate' ? 'bg-amber-50 text-amber-700' :
                    'bg-gray-50 text-gray-500'
                  }`}>{level}</span>
                </div>
              ))}
            </div>
          </div>

          <p className="text-xs text-gray-300 border-t pt-3">Generated by UNMAPPED · Powered by ISCO-08 + ESCO taxonomy</p>
        </div>

        <div className="flex flex-col gap-3 mt-5">
          <button
            onClick={handleDownloadPDF}
            disabled={exporting}
            className="w-full py-3 rounded-xl border-2 border-teal-400 text-teal-700 font-medium hover:bg-teal-50 transition-colors disabled:opacity-50"
          >
            {exporting ? 'Exporting...' : t('btn_download')}
          </button>
          <button
            onClick={() => navigate('/risk')}
            className="w-full py-3 rounded-xl bg-teal-500 hover:bg-teal-600 text-white font-medium transition-colors"
          >
            {t('btn_assess')} →
          </button>
        </div>
      </div>
    </div>
  )
}